import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Header, Footer } from '../components'
import { Providers } from '@/utils'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Wonski's Portfolio",
  description: 'Generated by Wonski',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className={inter.className}>
        <Providers>
          <div className="bg-primary">
            <Header />
            <div>{children}</div>
            <Footer />
            <div id="portal"></div>
          </div>
        </Providers>
      </body>
    </html>
  )
}
